# Generated by Django 3.0.11 on 2020-11-14 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_update', models.DateTimeField(auto_now_add=True, verbose_name='Data Atualização')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('quantity_stock', models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantidade em Estoque')),
            ],
            options={
                'verbose_name': 'Produto',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_update', models.DateTimeField(auto_now_add=True, verbose_name='Data Atualização')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantidade')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor Total')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Venda',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('dt_update', models.DateTimeField(auto_now_add=True, verbose_name='Data Atualização')),
                ('name', models.CharField(max_length=500, verbose_name='Nome')),
                ('url_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('cod_post', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publication'),
        ),
    ]
