# Generated by Django 3.0.11 on 2020-11-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='url_image',
            new_name='image',
        ),
    ]
