# Generated by Django 3.0.11 on 2020-11-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201114_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.TextField(verbose_name='Nome'),
        ),
    ]
