# Generated by Django 3.0.11 on 2020-11-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_publication_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
        migrations.AddField(
            model_name='publication',
            name='url_image',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
